name: Build .NET MAUI Android (.aab)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Decrypt keystore
        run: |
          mkdir -p $HOME/.keystore
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > $HOME/.keystore/myapp.keystore

      - name: Build Android AAB
        run: dotnet publish YourApp.csproj -f net8.0-android -c Release -o publish \
          /p:AndroidKeyStore=true \
          /p:AndroidSigningKeyStore=$HOME/.keystore/myapp.keystore \
          /p:AndroidSigningKeyAlias=${{ secrets.KEY_ALIAS }} \
          /p:AndroidSigningKeyPass=${{ secrets.KEY_PASS }} \
          /p:AndroidSigningStorePass=${{ secrets.STORE_PASS }} \
          /p:AndroidPackageFormat=aab

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-bundle
          path: publish/*.aab
