name: Build and Deploy JobClick to Google Play

on:
  workflow_dispatch:
    inputs:
      track:
        description: 'Play Store track to deploy (internal, alpha, beta, production)'
        required: true
        default: 'internal'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Install MAUI Android Workload
      run: dotnet workload install maui-android

    - name: Decode keystore
      run: |
        mkdir -p $HOME/.keystore
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > $HOME/.keystore/jobclick.keystore

    - name: Restore dependencies
      working-directory: JobClick
      run: dotnet restore JobClick.csproj -f net9.0-android35.0

    - name: Build Android AAB
      working-directory: JobClick
      run: |
        dotnet publish JobClick.csproj \
          -f net9.0-android35.0 \
          -c Release \
          -p:AndroidKeyStore=true \
          -p:AndroidSigningKeyAlias=${{ secrets.KEY_ALIAS }} \
          -p:AndroidSigningKeyPass=${{ secrets.KEY_PASSWORD }} \
          -p:AndroidSigningStorePass=${{ secrets.KEYSTORE_PASSWORD }} \
          -p:AndroidSigningKeyStore=$HOME/.keystore/jobclick.keystore \
          -o ./output

    - name: Upload to Play Store
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_JSON }}
        packageName: com.jobclick.app
        releaseFiles: JobClick/output/*.aab
        track: ${{ github.event.inputs.track }}
